[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit"

# Configurações de cache para melhor performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://app.datalitics.com.br https://cdn.datalitics.app https://www.google-analytics.com https://*.googleadservices.com https://*.g.doubleclick.net https://*.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://app.datalitics.com.br; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com https://*.google.com https://*.googleadservices.com https://*.doubleclick.net https://stats.g.doubleclick.net https://analytics.google.com https://www.google.com.br; frame-src 'self' https://www.googletagmanager.com https://td.doubleclick.net https://www.google.com https://app.netlify.com https://*.doubleclick.net;"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"